title: SNaP Lab
description: Internal website for the SNaP Lab
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://snaplab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
theme: just-the-docs

aux_links:
  Edit on GitHub: https://github.com/LindenParkesLab/snaplab.github.io
